### ISSUE TITLE
ER: clean old pipelines

### ISSUE THREAD

**Issue by imago-storm** [electric-cloud-community/EC-Admin#5]
_From @lrochette on September 22, 2017 13:46_

Create a new procedures to delete old pipelines

Potential parameters:
 - nbDays: older than X....
 - pattern: only delete pipelines that matches the name
 - project: delete only pipelines in a specific project

_Copied from original issue: electric-cloud/EC-Admin#119_

**Comment by lrochette** [comment]
Need to bump this as it was requested by customer

**Comment by lrochette** [comment]
Completed flowRuntimes can now be deleted
